import Modal from '@/components/Modal'
import './globals.css'
import type { Metadata } from 'next'
import AuthProvider from '@/context/AuthProvider'
import { Inter } from 'next/font/google'
import { UserProvider } from '@/context/UserContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Trello AI Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <AuthProvider>
          <UserProvider>
            <main className='h-screen'>
              {children}
            </main>
          </UserProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
