import Modal from '@/components/Modal'
import './globals.css'
import type { Metadata } from 'next'
import AuthProvider from '@/context/AuthProvider'
import { Inter } from 'next/font/google'
import { UserProvider } from '@/context/UserContext'
import Modals from '@/components/modals/Modals'
import getCurrentUser from '@/utils/getCurrentUser'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Trello AI Clone',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const user = await getCurrentUser()
  console.log('USER + ', user)
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <AuthProvider>
          <UserProvider>
            <main className='h-screen'>
              <Modals user={user}/>
              {children}
            </main>
          </UserProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
